#!/bin/bash

# https://stackoverflow.com/questions/3417896/
exec < /dev/tty

divider() {
    echo "************************************************"
}

echo "Pre-commit hook engaged."

divider
echo "Running unittests"
divider
hooks/unittests.sh


divider
echo "Now stripping output of IPython Notebooks"
divider
hooks/strip_jupyter.sh

divider
echo "Reformatting code using black"
divider
hooks/black.sh
