#!/bin/bash

# https://stackoverflow.com/questions/3417896/
exec < /dev/tty

echo "Pre-commit hook engaged."

####################
# run unit checks

read -p "Run unittests? [yY]" -n 1 -r
echo    # (optional) move to a new line
if [[ $REPLY =~ ^[Yy]$ ]]
then
    `python3 -m unittest discover `
    if [[ $? = 0 ]]
    then
        echo "Unittests passed."
    else
        echo "Unittests did not pass."
        exit 1
    fi
else
    echo "Skipping unit tests"
fi

####################
# strip output of IPython Notebooks
# FROM: https://gist.github.com/minrk/6176788

echo "Now stripping output of IPython Notebooks"

if git rev-parse --verify HEAD >/dev/null 2>&1; then
   against=HEAD
else
   # Initial commit: diff against an empty tree object
   against=4b825dc642cb6eb9a060e54bf8d69288fbee4904
fi

echo "checkpoint 3"

# Find notebooks to be committed
(
IFS='
'
NBS=`git diff-index $against --name-only | grep '\.ipynb$' | uniq`

for NB in $NBS ; do
    echo "Removing outputs from $NB"
    hooks/nbstripout "$NB"
    git add "$NB"
done
)

echo "checkpoint 4"

# exec git diff-index --check --cached $against --

echo "checkpoint 5"